apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: myapp
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth
          image: ghcr.io/${GITHUB_USER}/auth-service:__IMAGE_TAG__
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
