apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-logger
  labels:
    app: auth-logger
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: auth-logger
  template:
    metadata:
      labels:
        app: auth-logger
    spec:
      containers:
        - name: auth-logger
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          env:
{{- range .Values.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
{{- end }}
          resources: {{ toYaml .Values.resources | nindent 10 }}
