apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards-service
  namespace: myapp
  labels:
    app: cards-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cards-service
  template:
    metadata:
      labels:
        app: cards-service
    spec:
      containers:
        - name: cards
          image: ghcr.io/${GITHUB_USER}/cards-service:__IMAGE_TAG__
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
