replicaCount: 2
image:
  repository: ghcr.io/nik577/auth-logger
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  port: 8080
  type: ClusterIP

resources: {}
env:
  - name: DB_HOST
    value: pg-prod.database
  - name: DB_NAME
    value: postgres
  - name: DB_USER
    value: postgres
  - name: DB_PASS
    value: postgres
